[project]
name = "fabric-agent"
version = "0.1.0"
description = "Fabric DataOps by Anton Fernando"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "msal>=1.34.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
